In [ ]:

import pandas as pd
import numpy as np

# My attempt to follow Panda Notebooks created by Donne Martin


In [ ]:
ser_1 = pd.Series([1,1,2,3])
ser_1

In [5]:
ser_1.values


array([1, 1, 2, 3], dtype=int64)

In [6]:
ser_1.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
ser_2 =  pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
ser_2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
ser_2 *2

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [9]:
np.exp(ser_2)

a      2.718282
b      7.389056
c     20.085537
d     54.598150
e    148.413159
dtype: float64

In [10]:
dict_1 = {'apples':100, 'bananas' :200, 'pears':300}
ser_3 = pd.Series(dict_1)
ser_3

apples     100
bananas    200
pears      300
dtype: int64

In [11]:
index= ['apples','bananas','pears','oranges']
ser_4 = pd.Series(dict_1, index=index)
ser_4

apples     100.0
bananas    200.0
pears      300.0
oranges      NaN
dtype: float64

In [12]:
pd.isnull(ser_4)

apples     False
bananas    False
pears      False
oranges     True
dtype: bool

In [13]:
ser_3+ ser_4

apples     200.0
bananas    400.0
oranges      NaN
pears      600.0
dtype: float64

In [14]:
ser_4.name = 'Fruits'

In [15]:
ser_4.index.name = 'Name'

In [16]:
ser_4

Name
apples     100.0
bananas    200.0
pears      300.0
oranges      NaN
Name: Fruits, dtype: float64

In [17]:
data_1 = {'state':['Cali','Cali','Cali','NY','NY'],
          'year':[2000,2001,2002,2001,2002],
          'pop':[3.4,3.6,3.8,2.5,2.7]}
df_1 = pd.DataFrame(data_1)
df_1

pop state  year
0  3.4  Cali  2000
1  3.6  Cali  2001
2  3.8  Cali  2002
3  2.5    NY  2001
4  2.7    NY  2002

In [18]:
df_2 = pd.DataFrame(data_1, columns=['year','state','pop'])
df_2

year state  pop
0  2000  Cali  3.4
1  2001  Cali  3.6
2  2002  Cali  3.8
3  2001    NY  2.5
4  2002    NY  2.7

In [19]:
df_3 = pd.DataFrame(data_1, columns=['year','state','pop','unempl'])
df_3

year state  pop unempl
0  2000  Cali  3.4    NaN
1  2001  Cali  3.6    NaN
2  2002  Cali  3.8    NaN
3  2001    NY  2.5    NaN
4  2002    NY  2.7    NaN

In [20]:
df_3['state']


0    Cali
1    Cali
2    Cali
3      NY
4      NY
Name: state, dtype: object

In [22]:
df_3['year']

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

In [23]:
df_3.state

0    Cali
1    Cali
2    Cali
3      NY
4      NY
Name: state, dtype: object

In [24]:
df_3.ix[0]

C:\Users\Rigel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


year      2000
state     Cali
pop        3.4
unempl     NaN
Name: 0, dtype: object

In [25]:
df_3['unempl'] = np.arange(5)
df_3

year state  pop  unempl
0  2000  Cali  3.4       0
1  2001  Cali  3.6       1
2  2002  Cali  3.8       2
3  2001    NY  2.5       3
4  2002    NY  2.7       4

In [26]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
unempl = pd.Series([6.0,6.0,6.1], index =[0,2,4])
df_3['unempl'] = unempl
df_3

year state  pop  unempl
0  2000  Cali  3.4     6.0
1  2001  Cali  3.6     NaN
2  2002  Cali  3.8     6.0
3  2001    NY  2.5     NaN
4  2002    NY  2.7     6.1

In [28]:
df_3['state_dup'] = df_3['state']
df_3

year state  pop  unempl state_dup
0  2000  Cali  3.4     6.0      Cali
1  2001  Cali  3.6     NaN      Cali
2  2002  Cali  3.8     6.0      Cali
3  2001    NY  2.5     NaN        NY
4  2002    NY  2.7     6.1        NY

In [29]:
del df_3['state_dup']
df_3

year state  pop  unempl
0  2000  Cali  3.4     6.0
1  2001  Cali  3.6     NaN
2  2002  Cali  3.8     6.0
3  2001    NY  2.5     NaN
4  2002    NY  2.7     6.1

In [30]:
pop = {'Cali':{2001:3.6,2014:3.8},
      'NY': {2001:2.5, 2002:2.7}}
pop

{'Cali': {2001: 3.6, 2014: 3.8}, 'NY': {2001: 2.5, 2002: 2.7}}

In [31]:
df_4 = pd.DataFrame(pop)
df_4

Cali   NY
2001   3.6  2.5
2002   NaN  2.7
2014   3.8  NaN

In [32]:
df_4.T


2001  2002  2014
Cali   3.6   NaN   3.8
NY     2.5   2.7   NaN

In [33]:
df_4.T.T

Cali   NY
2001   3.6  2.5
2002   NaN  2.7
2014   3.8  NaN

In [34]:
data_2 = {'Cali':df_4['Cali'][1:],
          'NY' : df_4['NY'][2:]}
df_5 = pd.DataFrame(data_2)
df_5

Cali  NY
2002   NaN NaN
2014   3.8 NaN

In [35]:
df_5.index.name = 'year'
df_5

Cali  NY
year          
2002   NaN NaN
2014   3.8 NaN

In [36]:
df_5.columns.name = 'state'
df_5

state  Cali  NY
year           
2002    NaN NaN
2014    3.8 NaN

In [37]:
df_5.values

array([[ nan,  nan],
       [ 3.8,  nan]])

In [38]:
df_3.values

array([[2000, 'Cali', 3.4, 6.0],
       [2001, 'Cali', 3.6, nan],
       [2002, 'Cali', 3.8, 6.0],
       [2001, 'NY', 2.5, nan],
       [2002, 'NY', 2.7, 6.1]], dtype=object)

In [39]:
df_3

year state  pop  unempl
0  2000  Cali  3.4     6.0
1  2001  Cali  3.6     NaN
2  2002  Cali  3.8     6.0
3  2001    NY  2.5     NaN
4  2002    NY  2.7     6.1

In [40]:
df_3.unempl = [6.0,6.0, index = (1,3)]

SyntaxError: invalid syntax (<ipython-input-40-a493b665cefd>, line 1)

In [41]:
unempl = pd.Series([6.0,6.0], index = [1,3])
df_3['unempl'] =  unempl
df_3

year state  pop  unempl
0  2000  Cali  3.4     NaN
1  2001  Cali  3.6     6.0
2  2002  Cali  3.8     NaN
3  2001    NY  2.5     6.0
4  2002    NY  2.7     NaN

In [42]:
df_3

year state  pop  unempl
0  2000  Cali  3.4     NaN
1  2001  Cali  3.6     6.0
2  2002  Cali  3.8     NaN
3  2001    NY  2.5     6.0
4  2002    NY  2.7     NaN

In [43]:
df_3.reindex(list(reversed(range(0,6))))

year state  pop  unempl
5     NaN   NaN  NaN     NaN
4  2002.0    NY  2.7     NaN
3  2001.0    NY  2.5     6.0
2  2002.0  Cali  3.8     NaN
1  2001.0  Cali  3.6     6.0
0  2000.0  Cali  3.4     NaN

In [44]:
df_3.reindex(range(6,0),fill_value = 0)

Empty DataFrame
Columns: [year, state, pop, unempl]
Index: []

In [45]:
ser_5 = pd.Series(['apple','bananas','pears'], index= [0,2,4])
ser_5

0      apple
2    bananas
4      pears
dtype: object

In [46]:
ser_5.reindex(range(5), method = 'ffill')

0      apple
1      apple
2    bananas
3    bananas
4      pears
dtype: object

In [47]:
ser_5.reindex(range(10), method ='ffill')

0      apple
1      apple
2    bananas
3    bananas
4      pears
5      pears
6      pears
7      pears
8      pears
9      pears
dtype: object

In [48]:
ser_5 = pd.Series(['apple','bananas','pears'], index= [0,2,4])
ser_5.reindex(range(5), method = 'bfill')

0      apple
1    bananas
2    bananas
3      pears
4      pears
dtype: object

In [49]:
df_3.reindex(columns=['state','pop','unempl','year'])

state  pop  unempl  year
0  Cali  3.4     NaN  2000
1  Cali  3.6     6.0  2001
2  Cali  3.8     NaN  2002
3    NY  2.5     6.0  2001
4    NY  2.7     NaN  2002

In [50]:
df_3.reindex(columns = ['year', 'state', 'pop', 'unempl'])

year state  pop  unempl
0  2000  Cali  3.4     NaN
1  2001  Cali  3.6     6.0
2  2002  Cali  3.8     NaN
3  2001    NY  2.5     6.0
4  2002    NY  2.7     NaN

In [51]:
df_3

year state  pop  unempl
0  2000  Cali  3.4     NaN
1  2001  Cali  3.6     6.0
2  2002  Cali  3.8     NaN
3  2001    NY  2.5     6.0
4  2002    NY  2.7     NaN

In [52]:
df_3.reindex(index=list(reversed(range(0,6))),
             fill_value=0, 
             columns = ['state','pop','umempl','year'])

state  pop  umempl  year
5     0  0.0       0     0
4    NY  2.7       0  2002
3    NY  2.5       0  2001
2  Cali  3.8       0  2002
1  Cali  3.6       0  2001
0  Cali  3.4       0  2000

In [53]:
df_6 = df_3.ix[range(0,7),['state','pop','unempl','year']]
df_6

state  pop  unempl    year
0  Cali  3.4     NaN  2000.0
1  Cali  3.6     6.0  2001.0
2  Cali  3.8     NaN  2002.0
3    NY  2.5     6.0  2001.0
4    NY  2.7     NaN  2002.0
5   NaN  NaN     NaN     NaN
6   NaN  NaN     NaN     NaN

In [54]:
df_7 = df_6.drop([0,1])
df_7

state  pop  unempl    year
2  Cali  3.8     NaN  2002.0
3    NY  2.5     6.0  2001.0
4    NY  2.7     NaN  2002.0
5   NaN  NaN     NaN     NaN
6   NaN  NaN     NaN     NaN

In [55]:
df_7

state  pop  unempl    year
2  Cali  3.8     NaN  2002.0
3    NY  2.5     6.0  2001.0
4    NY  2.7     NaN  2002.0
5   NaN  NaN     NaN     NaN
6   NaN  NaN     NaN     NaN

In [56]:
df_7

state  pop  unempl    year
2  Cali  3.8     NaN  2002.0
3    NY  2.5     6.0  2001.0
4    NY  2.7     NaN  2002.0
5   NaN  NaN     NaN     NaN
6   NaN  NaN     NaN     NaN

In [57]:
ser_2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [58]:
ser_2[0]

1

In [59]:
ser_2[0] == ser_2['a']

True

In [60]:
ser_2[1:4]

b    2
c    3
d    4
dtype: int64

In [61]:
ser_2[['b','c','d']]

b    2
c    3
d    4
dtype: int64

In [62]:
ser_2[['b','c','d']] == ser_2[1:4]

b    True
c    True
d    True
dtype: bool

In [63]:
ser_2[ser_2>0]

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [64]:
ser_2[ser_2>3]

d    4
e    5
dtype: int64

In [65]:
ser_2[0:1]

a    1
dtype: int64

In [66]:
ser_2['a':'b'] = 0
ser_2

a    0
b    0
c    3
d    4
e    5
dtype: int64

In [67]:
df_6

state  pop  unempl    year
0  Cali  3.4     NaN  2000.0
1  Cali  3.6     6.0  2001.0
2  Cali  3.8     NaN  2002.0
3    NY  2.5     6.0  2001.0
4    NY  2.7     NaN  2002.0
5   NaN  NaN     NaN     NaN
6   NaN  NaN     NaN     NaN

In [68]:
df_6[['pop','unempl']]

pop  unempl
0  3.4     NaN
1  3.6     6.0
2  3.8     NaN
3  2.5     6.0
4  2.7     NaN
5  NaN     NaN
6  NaN     NaN

In [69]:
df_6[:2]

state  pop  unempl    year
0  Cali  3.4     NaN  2000.0
1  Cali  3.6     6.0  2001.0

In [70]:
df_6[df_6['pop']>3]

state  pop  unempl    year
0  Cali  3.4     NaN  2000.0
1  Cali  3.6     6.0  2001.0
2  Cali  3.8     NaN  2002.0

In [71]:
df_6 >5

state    pop  unempl   year
0   True  False   False   True
1   True  False    True   True
2   True  False   False   True
3   True  False    True   True
4   True  False   False   True
5   True  False   False  False
6   True  False   False  False

In [72]:
df_6[df_6>3]

state  pop  unempl    year
0  Cali  3.4     NaN  2000.0
1  Cali  3.6     6.0  2001.0
2  Cali  3.8     NaN  2002.0
3    NY  NaN     6.0  2001.0
4    NY  NaN     NaN  2002.0
5   NaN  NaN     NaN     NaN
6   NaN  NaN     NaN     NaN

In [73]:
df_6.ix[2:3]

C:\Users\Rigel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


state  pop  unempl    year
2  Cali  3.8     NaN  2002.0
3    NY  2.5     6.0  2001.0

In [74]:
df_6.ix[0:2,'pop']

0    3.4
1    3.6
2    3.8
Name: pop, dtype: float64

In [75]:
df_6.ix[df_6.unempl>5]

state  pop  unempl    year
1  Cali  3.6     6.0  2001.0
3    NY  2.5     6.0  2001.0

In [76]:
df_6[df_6.unempl>5]

state  pop  unempl    year
1  Cali  3.6     6.0  2001.0
3    NY  2.5     6.0  2001.0

In [77]:
np.random.seed(0)
ser_6 = pd.Series(np.random.randn(5),index = ['a','b','c','d','e'])
ser_6

a    1.764052
b    0.400157
c    0.978738
d    2.240893
e    1.867558
dtype: float64

In [78]:
ser_6['e']

1.8675579901499675

In [79]:
np.random.seed(1)
ser_7 = pd.Series(np.random.randn(5), index = ['a','c','e','f','g'])
ser_7

a    1.624345
c   -0.611756
e   -0.528172
f   -1.072969
g    0.865408
dtype: float64

In [80]:
ser_6+ ser_7

a    3.388398
b         NaN
c    0.366982
d         NaN
e    1.339386
f         NaN
g         NaN
dtype: float64

In [81]:
ser_6.add(ser_7)

a    3.388398
b         NaN
c    0.366982
d         NaN
e    1.339386
f         NaN
g         NaN
dtype: float64

In [82]:
ser_6.add(ser_7,fill_value= 0)

a    3.388398
b    0.400157
c    0.366982
d    2.240893
e    1.339386
f   -1.072969
g    0.865408
dtype: float64

In [83]:
np.random.seed(0)
df_8 = pd.DataFrame(np.random.rand(9).reshape((3,3)), 
                    columns = ['a','b','c'])
df_8

a         b         c
0  0.548814  0.715189  0.602763
1  0.544883  0.423655  0.645894
2  0.437587  0.891773  0.963663

In [84]:
np.random.seed(1)
df_8 = pd.DataFrame(np.random.rand(9).reshape((3,3)))
df_8

0         1         2
0  0.417022  0.720324  0.000114
1  0.302333  0.146756  0.092339
2  0.186260  0.345561  0.396767

In [85]:
np.random.seed(0)
df_8 = pd.DataFrame(np.random.rand(9).reshape((3,3)), 
                    columns = ['a','b','c'])
df_8

a         b         c
0  0.548814  0.715189  0.602763
1  0.544883  0.423655  0.645894
2  0.437587  0.891773  0.963663

In [86]:
np.random.seed(0)
df_9 = pd.DataFrame(np.random.rand(9).reshape((3,3)), 
                    columns = ['b','c','d'])
df_9

b         c         d
0  0.548814  0.715189  0.602763
1  0.544883  0.423655  0.645894
2  0.437587  0.891773  0.963663

In [87]:
df_8+df_9

a         b         c   d
0 NaN  1.264003  1.317953 NaN
1 NaN  0.968538  1.069549 NaN
2 NaN  1.329360  1.855436 NaN

In [88]:
df_10 =  df_8.add(df_9, fill_value = 0)
df_10

a         b         c         d
0  0.548814  1.264003  1.317953  0.602763
1  0.544883  0.968538  1.069549  0.645894
2  0.437587  1.329360  1.855436  0.963663

In [89]:
ser_8 = df_10.ix[0]
ser_8




C:\Users\Rigel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


a    0.548814
b    1.264003
c    1.317953
d    0.602763
Name: 0, dtype: float64

In [90]:
df_11 = df_10 - ser_8
df_11


a         b         c         d
0  0.000000  0.000000  0.000000  0.000000
1 -0.003930 -0.295465 -0.248404  0.043131
2 -0.111226  0.065357  0.537483  0.360899

In [91]:
ser_9 = pd.Series(range(3), index = ['a','d','e'])
ser_9

a    0
d    1
e    2
dtype: int32

In [92]:
df_11 - ser_9

a   b   c         d   e
0  0.000000 NaN NaN -1.000000 NaN
1 -0.003930 NaN NaN -0.956869 NaN
2 -0.111226 NaN NaN -0.639101 NaN

In [93]:
df_10

a         b         c         d
0  0.548814  1.264003  1.317953  0.602763
1  0.544883  0.968538  1.069549  0.645894
2  0.437587  1.329360  1.855436  0.963663

In [94]:
ser_10 = pd.Series([100,200,300])
ser_10

0    100
1    200
2    300
dtype: int64

In [95]:
df_10.sub (ser_10, axis=0)

a           b           c           d
0  -99.451186  -98.735997  -98.682047  -99.397237
1 -199.455117 -199.031462 -198.930451 -199.354106
2 -299.562413 -298.670640 -298.144564 -299.036337

In [96]:
df_11 =  np.abs(df_11)
df_11

a         b         c         d
0  0.000000  0.000000  0.000000  0.000000
1  0.003930  0.295465  0.248404  0.043131
2  0.111226  0.065357  0.537483  0.360899

In [97]:
df_11

a         b         c         d
0  0.000000  0.000000  0.000000  0.000000
1  0.003930  0.295465  0.248404  0.043131
2  0.111226  0.065357  0.537483  0.360899

In [98]:
func_1 = lambda x: x.max() - x.min()
df_11.apply(func_1)

a    0.111226
b    0.295465
c    0.537483
d    0.360899
dtype: float64

In [100]:
?lambda x

Object `lambda` not found.


In [101]:
df_11.apply(func_1,axis=1)

0    0.000000
1    0.291535
2    0.472126
dtype: float64

In [103]:
func_2 = lambda x: pd.Series([x.min(), x.max()], index = ['min','max'])
df_11.apply(func_2)

a         b         c         d
min  0.000000  0.000000  0.000000  0.000000
max  0.111226  0.295465  0.537483  0.360899

In [104]:
df_11

a         b         c         d
0  0.000000  0.000000  0.000000  0.000000
1  0.003930  0.295465  0.248404  0.043131
2  0.111226  0.065357  0.537483  0.360899

In [105]:
func_3 = lambda x: '%.2f' %x
df_11.applymap(func_3)

a     b     c     d
0  0.00  0.00  0.00  0.00
1  0.00  0.30  0.25  0.04
2  0.11  0.07  0.54  0.36

In [106]:
'%.2f'

'%.2f'

In [107]:
df_11['a'].map(func_3)

0    0.00
1    0.00
2    0.11
Name: a, dtype: object

In [108]:
ser_4

Name
apples     100.0
bananas    200.0
pears      300.0
oranges      NaN
Name: Fruits, dtype: float64

In [109]:
ser_4.sort_index

<bound method Series.sort_index of Name
apples     100.0
bananas    200.0
pears      300.0
oranges      NaN
Name: Fruits, dtype: float64>

In [111]:
df_12 = pd.DataFrame(np.arange(12).reshape((3,4)),
                    index = ['three','one','two'],
                    columns = ['c','a','b','d'])
df_12

c  a   b   d
three  0  1   2   3
one    4  5   6   7
two    8  9  10  11

In [112]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
pd.DataFrame(np.arange(12).reshape((3,4)))

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [123]:
df_12.sort_index()

c  a   b   d
one    4  5   6   7
three  0  1   2   3
two    8  9  10  11

In [124]:
df_12.sort_index(axis =1, ascending = False)

d  c   b  a
three   3  0   2  1
one     7  4   6  5
two    11  8  10  9

In [125]:
df_12.sort_values(by=['d','c'])

c  a   b   d
three  0  1   2   3
one    4  5   6   7
two    8  9  10  11

In [127]:
ser_11 = pd.Series([7,-5,6,4,2,0,4,7])
ser_11 = ser_11.sort_values()
ser_11

1   -5
5    0
4    2
3    4
6    4
2    6
0    7
7    7
dtype: int64

In [128]:
ser_11.rank()

1    1.0
5    2.0
4    3.0
3    4.5
6    4.5
2    6.0
0    7.5
7    7.5
dtype: float64

In [130]:
ser_11.rank(method='first')

1    1.0
5    2.0
4    3.0
3    4.0
6    5.0
2    6.0
0    7.0
7    8.0
dtype: float64

In [131]:
ser_11.rank(ascending= False, method = 'max')

1    8.0
5    7.0
4    6.0
3    5.0
6    5.0
2    3.0
0    2.0
7    2.0
dtype: float64

In [133]:
df_13 =  pd.DataFrame({'foo':[7,-5,7,4,2,0,4,7],
                    'bar':[-5,4,2,0,4,7,7,8],
                    'baz': [-1,2,3,0,5,9,9,5]})
df_13

bar  baz  foo
0   -5   -1    7
1    4    2   -5
2    2    3    7
3    0    0    4
4    4    5    2
5    7    9    0
6    7    9    4
7    8    5    7

In [134]:
df_13.rank()

bar  baz  foo
0  1.0  1.0  7.0
1  4.5  3.0  1.0
2  3.0  4.0  7.0
3  2.0  2.0  4.5
4  4.5  5.5  3.0
5  6.5  7.5  2.0
6  6.5  7.5  4.5
7  8.0  5.5  7.0

In [135]:
df_13.rank(axis=1)

bar  baz  foo
0  1.0  2.0  3.0
1  3.0  2.0  1.0
2  1.0  2.0  3.0
3  1.5  1.5  3.0
4  2.0  3.0  1.0
5  2.0  3.0  1.0
6  2.0  3.0  1.0
7  3.0  1.0  2.0

In [137]:
ser_12 = pd.Series(range(5),index = ['foo','foo','bar','bar','baz'])
ser_12

foo    0
foo    1
bar    2
bar    3
baz    4
dtype: int32

In [138]:
ser_12['foo']

foo    0
foo    1
dtype: int32

In [139]:
ser_12['bar']

bar    2
bar    3
dtype: int32

In [140]:
df_14 = pd.DataFrame(np.random.rand(5,4),
                     index = ['foo','foo','bar','bar','baz'])
df_14

0         1         2         3
foo  0.383442  0.791725  0.528895  0.568045
foo  0.925597  0.071036  0.087129  0.020218
bar  0.832620  0.778157  0.870012  0.978618
bar  0.799159  0.461479  0.780529  0.118274
baz  0.639921  0.143353  0.944669  0.521848

In [142]:
np.random.rand(5,4)

array([[ 0.41466194,  0.26455561,  0.77423369,  0.45615033],
       [ 0.56843395,  0.0187898 ,  0.6176355 ,  0.61209572],
       [ 0.616934  ,  0.94374808,  0.6818203 ,  0.3595079 ],
       [ 0.43703195,  0.6976312 ,  0.06022547,  0.66676672],
       [ 0.67063787,  0.21038256,  0.1289263 ,  0.31542835]])

In [143]:
df_14.ix['bar']

C:\Users\Rigel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


0         1         2         3
bar  0.832620  0.778157  0.870012  0.978618
bar  0.799159  0.461479  0.780529  0.118274

In [144]:
df_6

state  pop  unempl    year
0  Cali  3.4     NaN  2000.0
1  Cali  3.6     6.0  2001.0
2  Cali  3.8     NaN  2002.0
3    NY  2.5     6.0  2001.0
4    NY  2.7     NaN  2002.0
5   NaN  NaN     NaN     NaN
6   NaN  NaN     NaN     NaN

In [145]:
df_6.sum()

pop          16.0
unempl       12.0
year      10006.0
dtype: float64

In [146]:
df_6.sum(axis=1)

0    2003.4
1    2010.6
2    2005.8
3    2009.5
4    2004.7
5       0.0
6       0.0
dtype: float64

In [147]:
df_6.sum(axis =1,skipna=False)

0       NaN
1    2010.6
2       NaN
3    2009.5
4       NaN
5       NaN
6       NaN
dtype: float64

In [149]:
data_1 = {'state':['VA','VA','VA','MD','MD'],
          'year':[2012,2013,2014,2014,2015],
          'population':[5.0,5.1,5.2,4.0,4.1]}
df_1 = pd.DataFrame(data_1)
df_1

population state  year
0         5.0    VA  2012
1         5.1    VA  2013
2         5.2    VA  2014
3         4.0    MD  2014
4         4.1    MD  2015

In [151]:
df_1.replace('VA','VIRGINIA', inplace= True)
df_1

population     state  year
0         5.0  VIRGINIA  2012
1         5.1  VIRGINIA  2013
2         5.2  VIRGINIA  2014
3         4.0        MD  2014
4         4.1        MD  2015

In [153]:
df_1.replace({'state':{'MD':'MARYLAND'}},inplace=True)
df_1

population     state  year
0         5.0  VIRGINIA  2012
1         5.1  VIRGINIA  2013
2         5.2  VIRGINIA  2014
3         4.0  MARYLAND  2014
4         4.1  MARYLAND  2015

In [154]:
df_2 = df_1.drop('population', axis=1)
df_2

state  year
0  VIRGINIA  2012
1  VIRGINIA  2013
2  VIRGINIA  2014
3  MARYLAND  2014
4  MARYLAND  2015

In [155]:
data_2 = {'state':['NY','NY','NY','FL','FL'],
         'year': [2012,2013,2014,2014,2015],
         'population':[6.0,6.1,6.2,3.0,3.1]}
df_3 = pd.DataFrame(data_2)
df_3

population state  year
0         6.0    NY  2012
1         6.1    NY  2013
2         6.2    NY  2014
3         3.0    FL  2014
4         3.1    FL  2015

In [156]:
df_4 = pd.concat([df_1,df_3])
df_4

population     state  year
0         5.0  VIRGINIA  2012
1         5.1  VIRGINIA  2013
2         5.2  VIRGINIA  2014
3         4.0  MARYLAND  2014
4         4.1  MARYLAND  2015
0         6.0        NY  2012
1         6.1        NY  2013
2         6.2        NY  2014
3         3.0        FL  2014
4         3.1        FL  2015

In [161]:
df_1 = pd.read_csv("C:/Users/Rigel/Desktop/ozone.csv")
df_1

Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
5     28.0      NaN  14.9    66      5    6
6     23.0    299.0   8.6    65      5    7
7     19.0     99.0  13.8    59      5    8
8      8.0     19.0  20.1    61      5    9
9      NaN    194.0   8.6    69      5   10
10     7.0      NaN   6.9    74      5   11
11    16.0    256.0   9.7    69      5   12
12    11.0    290.0   9.2    66      5   13
13    14.0    274.0  10.9    68      5   14
14    18.0     65.0  13.2    58      5   15
15    14.0    334.0  11.5    64      5   16
16    34.0    307.0  12.0    66      5   17
17     6.0     78.0  18.4    57      5   18
18    30.0    322.0  11.5    68      5   19
19    11.0     44.0   9.7    62      5   20
20     1.0      8.0   9.7    59      5   21
21    11.0    320.0  16.6    73      5   22
22     4.0     25.0   9.7    61      5   23
23    32.0     92.0  12.0    61      5   24
24     NaN     66.0  16.6    57      5   25
25     NaN    266.0  14.9    58      5   26
26     NaN      NaN   8.0    57      5   27
27    23.0     13.0  12.0    67      5   28
28    45.0    252.0  14.9    81      5   29
29   115.0    223.0   5.7    79      5   30
..     ...      ...   ...   ...    ...  ...
123   96.0    167.0   6.9    91      9    1
124   78.0    197.0   5.1    92      9    2
125   73.0    183.0   2.8    93      9    3
126   91.0    189.0   4.6    93      9    4
127   47.0     95.0   7.4    87      9    5
128   32.0     92.0  15.5    84      9    6
129   20.0    252.0  10.9    80      9    7
130   23.0    220.0  10.3    78      9    8
131   21.0    230.0  10.9    75      9    9
132   24.0    259.0   9.7    73      9   10
133   44.0    236.0  14.9    81      9   11
134   21.0    259.0  15.5    76      9   12
135   28.0    238.0   6.3    77      9   13
136    9.0     24.0  10.9    71      9   14
137   13.0    112.0  11.5    71      9   15
138   46.0    237.0   6.9    78      9   16
139   18.0    224.0  13.8    67      9   17
140   13.0     27.0  10.3    76      9   18
141   24.0    238.0  10.3    68      9   19
142   16.0    201.0   8.0    82      9   20
143   13.0    238.0  12.6    64      9   21
144   23.0     14.0   9.2    71      9   22
145   36.0    139.0  10.3    81      9   23
146    7.0     49.0  10.3    69      9   24
147   14.0     20.0  16.6    63      9   25
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

In [163]:
df_1.describe()

Ozone     Solar.R        Wind        Temp       Month         Day
count  116.000000  146.000000  153.000000  153.000000  153.000000  153.000000
mean    42.129310  185.931507    9.957516   77.882353    6.993464   15.803922
std     32.987885   90.058422    3.523001    9.465270    1.416522    8.864520
min      1.000000    7.000000    1.700000   56.000000    5.000000    1.000000
25%     18.000000  115.750000    7.400000   72.000000    6.000000    8.000000
50%     31.500000  205.000000    9.700000   79.000000    7.000000   16.000000
75%     63.250000  258.750000   11.500000   85.000000    8.000000   23.000000
max    168.000000  334.000000   20.700000   97.000000    9.000000   31.000000

In [164]:
df_1.head()

Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5